### ISSUE TITLE
Create project from model

### ISSUE THREAD

**Issue by Daxture** [shashisadasivan/SSD365VSAddIn#12]
It would be nice to have an option to include all objects from a model into the visual studio project? For instance, I would like to create a project from a model which includes all the objects from the model and put into the project.

**Comment by TrudAX** [comment]
It seems like a standard function. just filter by the model and add results to the project
![image](https://user-images.githubusercontent.com/26786918/62502396-84f47680-b832-11e9-9c44-c0decae7a165.png)
