### ISSUE TITLE
Label in string

### ISSUE THREAD

**Issue by krconnect** [shashisadasivan/SSD365VSAddIn#14]
Is it possible to use the addin to add a label to a string? following example:  throw error(strFmt("message example", "Test"));

**Comment by shashisadasivan** [comment]
@krconnect that was something i was thinking about too :)
Wondering if we can do that by parsing the entire code as a string and finding labels marked under double inverted commas.

**Comment by shashisadasivan** [comment]
> @shashisadasivan I don't know how to pop up the addins menu in a selected string. do you have any idea?

@krconnect will probably need to read the entire source code for the class / table / dataEntity, and parse it to find a pattern on this.

**Comment by shashisadasivan** [comment]
@krconnect you may try this out now :)
I think i will need to make it work for attributes as well on methods. Currently the way you can scan code is by going through each method and getting the source code as a string. So may need to make this work for attributes as well.

Thanks for this suggestion.

**Comment by krconnect** [comment]
@shashisadasivan hi! how wonderful! how do I use it, because this option does not appear for me to test.

**Comment by shashisadasivan** [comment]
> @shashisadasivan hi! how wonderful! how do I use it, because this option does not appear for me to test.

https://www.youtube.com/watch?v=uxZp7mF0cWA

**Comment by krconnect** [comment]
Fantastic!!! Now I understand, is that my addins did not update. This new option did not appear. I'll see what happened. Thank you very much. It is perfect! 
I had to uncheck Build Events \ Post - Build event command line, as the error was occurring. Do you think this could be it? 

Severity	Code	Description	Project	File	Line	Suppression State
Error		The command "echo "----"
echo "--> Copy to Outputdlls"
copy C:\Users\Admind034f8d3e9\Downloads\SSD365VSAddIn-master (1)\SSD365VSAddIn-master\SSD365VSAddIn\SSD365VSAddIn\bin\Debug\SSD365VSAddIn.dll C:\Users\Admind034f8d3e9\Downloads\SSD365VSAddIn-master (1)\SSD365VSAddIn-master\SSD365VSAddIn\SSD365VSAddIn\..\..\OutputDlls\SSD365VSAddIn.dll
echo "<-- Copy Complete"" exited with code 1.	SSD365VSAddIn

**Comment by krconnect** [comment]
@shashisadasivan can't update a .dll already restarted visual studio and the addins don't show a new option. Do you know what I can do?

I already copied SSD365VSAddIn.dll and Newtonsoft.Json.dll to the folder C: \ D365CustomAddIns

<?xml version="1.0" encoding="utf-8"?>
<DynamicsDevConfig xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/dynamics/2012/03/development/configuration">
	<AddInPaths xmlns:d2p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
		<d2p1:string>C:\D365CustomAddIns</d2p1:string>
	</AddInPaths>.......

**Comment by shashisadasivan** [comment]
> @shashisadasivan can't update a .dll already restarted visual studio and the addins don't show a new option. Do you know what I can do?
> 
> I already copied SSD365VSAddIn.dll and Newtonsoft.Json.dll to the folder C: \ D365CustomAddIns
> 
> C:\D365CustomAddIns .......

Can you empty out that folder, then start VS - the Addins should dissapear.
Close VS, then Copy the 2 dll's into that folder and start VS

**Comment by krconnect** [comment]
It worked !!! Thank you !!! Since you work with many developers, you always encounter a number of merge-related issues when it comes to generating a package. To avoid this, decide to create an entity in powerapps to control the tag file. Within the LabelHelper class, you can make a call in Microsoft Flow, or execute a flow and write an entity in powerapps. Then labelId is ignored on the developer's local machine, ie it uses the sequential number that is not in powerapps (azure). When we generate or build, we have another flow in Microsoft Flow, which generates the tag file and acidifies the project to generate the build. Thanks for the great help!

This was an idea we had to avoid wasting time solving problems with label merge.
