### ISSUE TITLE
Capture loggerd in user

### ISSUE THREAD

**Issue by krconnect** [shashisadasivan/SSD365VSAddIn#15]
@shashisadasivan hi, is it possible to get the username that is atuthenticate in visual studio using  the addins?

**Comment by shashisadasivan** [comment]
I am not sure about this. Have you tried searching for this? https://stackoverflow.com/questions/31353014/accessing-current-microsoft-account-from-visual-studio-extension
Also any reason why you wou;d want to include this in the extension ?

**Comment by krconnect** [comment]
I will use this information to know who created the label

**Comment by shashisadasivan** [comment]
> I will use this information to know who created the label

So this is not relevant to this extension then.
Have a look at the above link i sent. 
However source control might be a better fit for your requirement.
