### ISSUE TITLE
Create label in code - avoid commented line

### ISSUE THREAD

**Issue by shashisadasivan** [shashisadasivan/SSD365VSAddIn#21]
The addin to create labels for code, should exclude lines where it is a part of the comment

Original code:
`/// <summary>
///
/// </summary>
/// <param name="sender">sender</param>
/// <param name="e">Value</param>`

New code (bug)
`/// <summary>
    /// init value event handler
    /// </summary>
    /// <param name = "@MyLabel:Sender">sender</param>
    /// <param name = "@MyLabel:E">e</param>`

**Comment by globefire** [comment]
Can I do it @shashisadasivan?

**Comment by shashisadasivan** [comment]
> Can I do it @shashisadasivan?

Yes you can :) Thankyou
