### ISSUE TITLE
Help Debug Create Label

### ISSUE THREAD

**Issue by krconnect** [shashisadasivan/SSD365VSAddIn#26]
hi @shashisadasivan , how do i debug d365fo label creation?

**Comment by shashisadasivan** [comment]
@krconnect is this part of #22 ?
Have you got a VM with D365 finOps installed ?

**Comment by krconnect** [comment]
@shashisadasivan hello, yes i have a vm with d365fo installed.

**Comment by shashisadasivan** [comment]
@krconnect To debug the VS Addin code:
1. First open VS with the VS add inproject
2. Open a second VS instance and open a D365 project
3. From the first instance (with the VS add in project), attach the solution to a process (Debub > Attach to process) & select devenv.exe
This will now allow you to debug the code that runs in the Add in

For the Labels:
Look for the files under the Labels directory: lAbelCreatorMainMenuAddIn.cs, LabelFactory.cs, LabelHelper.cs

Let me also know which issue you are looking at
