### ISSUE TITLE
Help to Create Label in Configuration Key and Reports

### ISSUE THREAD

**Issue by krconnect** [shashisadasivan/SSD365VSAddIn#27]
@shashisadasivan Is it possible to label the configuration keys and Reports?

**Comment by shashisadasivan** [comment]
In the configuration key Yes
in the report - possibly no at this stage. The report will be a bit more comolicated as you would need to parse the XML file and manipulate the text in there (similar to the label in code)

**Comment by shashisadasivan** [comment]
Closing this
Report labels not supported at this stage :(
