### ISSUE TITLE
Object reference not set to an instance of an object / Could not load type 

### ISSUE THREAD

**Issue by swidz** [shashisadasivan/SSD365VSAddIn#42]
On a new VHD 10.0.9 + 10.0.10 update installed I am not able to use the tools.
After installation I am not able to open Dynamics 365 > Addins > Model settings (SS D365)

Depending on what is highlight in the solution explorer / designer view I get the following errors:

_Could not load type 'Microsoft.Dynamics.Framework.Tools.MetaModel.Core.ServiceLocator' from assembly 'Microsoft.Dynamics.Framework.Tools.Integrations, Version=7.0.0.0, Culture=neutral,PublicKeyToken=31bf3856ad364e35'_

or

_'Object reference not set to an instance of an object'_

I have also tried without an solution open, same result.

**Comment by swidz** [comment]
Sorry, I just saw you placed an update 15 hours ago :)

**Comment by shashisadasivan** [comment]
There has been a breaking change with 10.0.10 So old ones dont work anymore :( 
I doubt this is backwards compatible too.
But glad you answered yourself though 👍
