### ISSUE TITLE
Generate labels for form properties

### ISSUE THREAD

**Issue by celuxcwb** [shashisadasivan/SSD365VSAddIn#59]
First of all, I would like to congratulate you for the extension, which is very complete and easy to use, which has saved a lot of time for me and my team.
I am currently running version 10.0.26 in my development environment with Visual Studio 2019 and I noticed that the functionality of adding label to form properties is not working the same way as for tables, menusitens and classes.
Does any update is needed for this version.

Thanks again for the extension.

**Comment by celuxcwb** [comment]
Hi, I fix the error in labelfactory and send to you a commit with the code change. When can be possible, please get a pull to the master Branch.

This Issue can be finished.

**Comment by shashisadasivan** [comment]
Thanks @celuxcwb 
I'm glad its worked along so far and thank you for taking the time to fix it.
Any chances you haven't done a PR yet? as i haven't received the change.
