### ISSUE TITLE
Debug in Visual Studio 2019

### ISSUE THREAD

**Issue by krconnect** [shashisadasivan/SSD365VSAddIn#61]
@shashisadasivan hello, i'm using visual studio 2019 with D365FO. I'm trying to run the addin but I have the error below:

<img width="648" alt="Capture" src="https://user-images.githubusercontent.com/28067580/207364033-8fdbd082-1282-4570-86f1-93d7b079d551.PNG">

**Comment by krconnect** [comment]
yeap

**Comment by shashisadasivan** [comment]
Sorry, couldnt figure out what you meant by the error? Did you miss including the error message ?

**Comment by krconnect** [comment]
> 

@shashisadasivan I'm sorry it wasn't an error, it just wasn't stopping at the breakpoint, but I changed it to x86 and it worked.

**Comment by krconnect** [comment]
@shashisadasivan It's not stopping at all breakpoints, when I click to add labels it doesn't add. I'm using visual studio 2019. Do you know if there is any specific dll that I should replace?

<img width="551" alt="Capture1" src="https://user-images.githubusercontent.com/28067580/207454197-f7f9f674-8414-4853-acca-7b2ecceffd4a.PNG">
<img width="844" alt="Capture2" src="https://user-images.githubusercontent.com/28067580/207454718-4815fa57-568d-4335-b5eb-94f6e13bb14f.PNG">

**Comment by shashisadasivan** [comment]
You probably want to use "Create label for properties" instead of "Create
label in code"

**Comment by shashisadasivan** [comment]
> > 
> 
> @shashisadasivan I'm sorry it wasn't an error, it just wasn't stopping at the breakpoint, but I changed it to x86 and it worked.

ok. Good to know. Yes D365 is x86 based and hence why the memory issues with Visual studio.
However, can you let me know what the issue is you are facing? or this ticket can be closed?

**Comment by krconnect** [comment]
> 

can this ticket be closed please
