### ISSUE TITLE
Application Explorer not showing "Add-ins" in context menu in Visual Studio 2019

### ISSUE THREAD

**Issue by Celica64** [shashisadasivan/SSD365VSAddIn#63]
"Add-ins" menu item not showing up in Application Explorer.

![image](https://github.com/shashisadasivan/SSD365VSAddIn/assets/95567506/0fe70b60-ba27-4680-8865-ebae6fe694fb)

Menu items do show up in Dynamics 365\Add-ins.

![image](https://github.com/shashisadasivan/SSD365VSAddIn/assets/95567506/ee5c92cf-6367-45e5-9b27-8cc555328202)

Configuration file C:\Users\Admin5db9a2be63\Documents\Visual Studio Dynamics 365\DynamicsDevConfig.xml was updated by *iex*

```
<AddInPaths xmlns:d2p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
  <d2p1:string>T:\Bin\AddInExtensions</d2p1:string>
  <d2p1:string>C:\d365_VS_AddIns</d2p1:string>
</AddInPaths>

```

Visual studio version: Microsoft Visual Studio Professional 2019 Version 16.11.27

**Comment by Celica64** [comment]
It does show up in design window, use "View designer" first!

![image](https://github.com/shashisadasivan/SSD365VSAddIn/assets/95567506/e8d850c5-885c-46a8-b1f7-f63d239f1348)

**Comment by shashisadasivan** [comment]
> It does show up in design window, use "View designer" first!
> 
> ![image](https://user-images.githubusercontent.com/95567506/256196051-e8d850c5-885c-46a8-b1f7-f63d239f1348.png)

Yes that right, it only shows up in the designer context menu.
The AOT context seems to require duplicating a of the standard D365 template things which i didnt want to (thats what i found back then when i started this project)
